---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kubeovn-io-v1-configuration
  failurePolicy: Fail
  name: mconfiguration-v1.kb.io
  rules:
  - apiGroups:
    - kubeovn.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - configurations
  sideEffects: None
