# This rule is not used by the project kubeovn-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to kubeovn.io.my.domain resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubeovn-operator
    app.kubernetes.io/managed-by: kustomize
  name: configuration-viewer-role
rules:
- apiGroups:
  - kubeovn.io.my.domain
  resources:
  - configurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeovn.io.my.domain
  resources:
  - configurations/status
  verbs:
  - get
