package render

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net"
	"strconv"
	"strings"
	"text/template"

	"github.com/Masterminds/sprig/v3"
	ovnoperatorv1 "github.com/harvester/kubeovn-operator/api/v1"
	"github.com/harvester/kubeovn-operator/internal/templates"
	"helm.sh/helm/v4/pkg/engine"
	admissionregistrationv1 "k8s.io/api/admissionregistration/v1"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	rbacv1 "k8s.io/api/rbac/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/client-go/rest"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/yaml"
)

type values struct {
	Values ovnoperatorv1.ConfigurationSpec `json:"Values"`
}

func GenerateObjects(templates []string, config *ovnoperatorv1.Configuration, object client.Object, restConfig *rest.Config, version string, caCert string) ([]client.Object, error) {
	var returnedObjects []client.Object

	// patch version supplied by the controller
	config.Spec.Global.Images.KubeOVNImage.Tag = version

	valsObj, err := generateMap(config)
	if err != nil {
		return nil, fmt.Errorf("failed to generate values: %w", err)
	}

	err = unstructured.SetNestedField(valsObj, config.GetNamespace(), "Values", "namespace")
	if err != nil {
		return nil, fmt.Errorf("failed to set namespace field in values map: %v", err)
	}

	// add caCert for kubeovn operator to values this is used by the kubeovn validating webhook
	// the helm chart for kubeovn-operator already contains the SAN for kubeovn-webhook
	// to ensure this works seamlessly
	err = unstructured.SetNestedField(valsObj, caCert, "Values", "caCert")
	if err != nil {
		return nil, fmt.Errorf("failed to set caCert field in values map: %v", err)
	}

	if err := validateService(config); err != nil {
		return nil, err
	}

	// additional fields needed which are generated by the helper template in the helm chart
	kubeovn := generateIncludeValues(config)
	valsObj["kubeovn"] = kubeovn
	masterNodes := strings.Join(config.Status.MatchingNodeAddresses, ",")
	err = unstructured.SetNestedField(valsObj, masterNodes, "Values", "MASTER_NODES")
	if err != nil {
		return nil, fmt.Errorf("failed to set field MASTER_NODES in values map: %v", err)
	}

	// generate master node affinity and add to values so that it can be included in the templates where needed
	masterNodeAffinity, err := generateMasterNodeAffinity(config)
	if err != nil {
		return nil, fmt.Errorf("failed to generate master node affinity: %v", err)
	}
	if masterNodeAffinity != "" {
		err = unstructured.SetNestedField(valsObj, masterNodeAffinity, "kubeovn", "masterNodeAffinity")
		if err != nil {
			return nil, fmt.Errorf("failed to set field masterNodeAffinity in values map: %v", err)
		}
	}

	for _, sourceTemplate := range templates {
		returnedObject, err := generateObject(sourceTemplate, valsObj, object, restConfig)
		if err != nil {
			return nil, fmt.Errorf("error returned from generateTemplate: %v", err)
		}
		if returnedObject != nil {
			returnedObjects = append(returnedObjects, returnedObject)
		}
	}
	return returnedObjects, nil
}

func generateObject(input string, valuesObj map[string]interface{}, object client.Object, restConfig *rest.Config) (client.Object, error) {
	newObj := InitialiseNewObject(object)
	if newObj == nil {
		return nil, fmt.Errorf("could not initialise new object for type: %T", object)
	}
	var output bytes.Buffer
	f := sprig.TxtFuncMap()
	if restConfig != nil {
		f["lookup"] = engine.NewLookupFunction(restConfig)
	} else {
		// During unit tests/template rendering without a Kubernetes client,
		// behave like Helm lookup when the object does not exist.
		f["lookup"] = func(_ string, _ string, _ string, _ string) (map[string]interface{}, error) {
			return map[string]interface{}{}, nil
		}
	}
	f["include"] = include
	f["toYaml"] = func(v interface{}) string {
		data, err := yaml.Marshal(v)
		if err != nil {
			return ""
		}
		return strings.TrimSuffix(string(data), "\n")
	}
	tmpl := template.Must(template.New("objects").Funcs(f).Parse(input))
	err := tmpl.Execute(&output, valuesObj)
	if err != nil {
		return nil, fmt.Errorf("error rending template: %v", err)
	}
	// object is skipped due to condition in the template
	if strings.TrimSpace(output.String()) == "" {
		return nil, nil
	}

	err = yaml.Unmarshal(output.Bytes(), newObj)
	if err != nil {
		return nil, err
	}
	return newObj, nil
}

// needed to assert convert ensure templates need little to no change at all
func generateMap(config *ovnoperatorv1.Configuration) (map[string]interface{}, error) {
	val := values{Values: config.Spec}
	out, err := json.Marshal(val)
	if err != nil {
		return nil, err
	}

	resultMap := make(map[string]interface{})
	err = json.Unmarshal(out, &resultMap)
	return resultMap, err
}

// generateIncludeValues renders the values generated the _helpers.tpl in the chart
/*func generateIncludeValues(config *ovnoperatorv1.Configuration) map[string]interface{} {
	nodeIPS := strings.Join(config.Status.MatchingNodeAddresses, ",")
	upgradeStratergyMap := map[string]interface{}{
		"updateStrategy": "RollingUpdate",
	}

	// https://github.com/kubernetes/apimachinery/blob/v0.32.1/pkg/runtime/converter.go#L614
	// converter only supports int64 and float64, which is why the forced type conversion
	// for versionCompatability and runAsUser
	versionCompatibiltyMap := map[string]interface{}{
		"versionCompatibility": float64(24.03),
	}

	runAsUser := int64(65534)
	if *config.Spec.Component.EnableOVNIPSec {
		runAsUser = int64(0)
	}

	return map[string]interface{}{
		"nodeCount": int64(len(config.Status.MatchingNodeAddresses)),
		"nodeIPs":   nodeIPS,
		"ovs-ovn":   upgradeStratergyMap,
		"ovn":       versionCompatibiltyMap,
		"runAsUser": runAsUser,
	}

}*/

// mimic helm include but in this case values are already pre-calculate in the
// map when we render the values
func include(key string, data map[string]interface{}) interface{} {
	// split key into fields

	fields := strings.Split(key, ".")
	val, _, _ := unstructured.NestedFieldCopy(data, fields...)
	return val
}

func InitialiseNewObject(object client.Object) client.Object {
	switch object.(type) {
	case *appsv1.Deployment:
		return &appsv1.Deployment{}
	case *apiextensionsv1.CustomResourceDefinition:
		return &apiextensionsv1.CustomResourceDefinition{}
	case *corev1.Secret:
		return &corev1.Secret{}
	case *corev1.ServiceAccount:
		return &corev1.ServiceAccount{}
	case *corev1.ConfigMap:
		return &corev1.ConfigMap{}
	case *rbacv1.RoleBinding:
		return &rbacv1.RoleBinding{}
	case *rbacv1.ClusterRole:
		return &rbacv1.ClusterRole{}
	case *rbacv1.Role:
		return &rbacv1.Role{}
	case *rbacv1.ClusterRoleBinding:
		return &rbacv1.ClusterRoleBinding{}
	case *appsv1.DaemonSet:
		return &appsv1.DaemonSet{}
	case *corev1.Service:
		return &corev1.Service{}
	case *corev1.PersistentVolumeClaim:
		return &corev1.PersistentVolumeClaim{}
	case *admissionregistrationv1.ValidatingWebhookConfiguration:
		return &admissionregistrationv1.ValidatingWebhookConfiguration{}
	}

	return nil
}

func GenerateNorthBoundCleanupScript(nodeAddress string) (string, error) {
	return generateScript(nodeAddress, templates.CleanupNBDB)
}

func GenerateSouthBoundCleanupScript(nodeAddress string) (string, error) {
	return generateScript(nodeAddress, templates.CleanupSBDB)
}

func generateScript(nodeAddress, script string) (string, error) {
	values := map[string]string{
		"NodeAddress": nodeAddress,
	}
	tmpl, err := template.New("script").Parse(script)
	if err != nil {
		return "", fmt.Errorf("error parsing template %s: %v", script, err)
	}
	var result bytes.Buffer
	err = tmpl.Execute(&result, values)
	if err != nil {
		return "", fmt.Errorf("error during template execution %s using values %v: %v", script, values, err)
	}
	return result.String(), nil
}

func GenerateChassisCleanupScript(hostname string) (string, error) {
	values := map[string]string{
		"Hostname": hostname,
	}
	tmpl, err := template.New("script").Parse(templates.CleanupChassis)
	if err != nil {
		return "", fmt.Errorf("error parsing chassis cleanup template %s: %v", templates.CleanupChassis, err)
	}
	var result bytes.Buffer
	err = tmpl.Execute(&result, values)
	if err != nil {
		return "", fmt.Errorf("error during template execution %s using values %v: %v", templates.CleanupChassis, values, err)
	}
	return result.String(), nil
}

func generateMasterNodeAffinity(config *ovnoperatorv1.Configuration) (string, error) {

	// if there are no MasterNodeLabels return empty string
	if config.Spec.MasterNodesLabel == "" {
		return "", nil
	}

	podAffinityTemplate := `{{- $parts := splitList "=" .Spec.MasterNodesLabel -}}
{{- $key := index $parts 0 -}}
{{- $val := "" -}}
{{- if gt (len $parts) 1 -}}
  {{- $val = join "=" (rest $parts) -}}
{{- end -}}
nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
      - matchExpressions:
          - key: {{ $key }}
          {{- if ne $val "" }}
            operator: In
            values:
              - {{ $val | quote }}
          {{- else }}
            operator: Exists
          {{- end }}`
	f := sprig.TxtFuncMap()
	masterNodeAffinityTmpl, err := template.New("masterNodeAffinity").Funcs(f).Parse(podAffinityTemplate)
	if err != nil {
		return "", fmt.Errorf("error parsing master node affinity template: %v", err)
	}
	var result bytes.Buffer
	err = masterNodeAffinityTmpl.Execute(&result, config)
	if err != nil {
		return "", fmt.Errorf("error during master node affinity template execution using config %v: %v", config, err)
	}
	return result.String(), nil
}

func validateService(config *ovnoperatorv1.Configuration) error {
	service := config.Spec.OVNCentral.Service

	if service.Type == corev1.ServiceTypeLoadBalancer &&
		service.LoadBalancerIP == "" {
		return fmt.Errorf(
			"ovn-central.service.type=LoadBalancer requires ovn-central.service.loadBalancerIP to be set",
		)
	}

	return nil
}

func externalOVNAddress(endpoint string, port int64) string {
	if endpoint == "" {
		return ""
	}

	return "tcp:" + net.JoinHostPort(
		endpoint,
		strconv.Itoa(int(port)),
	)
}

// generateIncludeValues renders the values generated by _helpers.tpl in the Helm chart.
// These values are added under .Values.kubeovn because the custom include()
// implementation looks up pre-calculated helper values from this map.
func generateIncludeValues(config *ovnoperatorv1.Configuration) map[string]interface{} {
	nodeIPs := strings.Join(config.Status.MatchingNodeAddresses, ",")

	upgradeStrategyMap := map[string]interface{}{
		"updateStrategy": "RollingUpdate",
	}

	// https://github.com/kubernetes/apimachinery/blob/v0.32.1/pkg/runtime/converter.go#L614
	// converter only supports int64 and float64, which is why the forced type conversion
	// is used for versionCompatibility and runAsUser.
	versionCompatibilityMap := map[string]interface{}{
		"versionCompatibility": float64(24.03),
	}

	runAsUser := int64(65534)
	if config.Spec.Component.EnableOVNIPSec != nil && *config.Spec.Component.EnableOVNIPSec {
		runAsUser = int64(0)
	}

	// -------------------------------------------------------------------------
	// ovn-central HCP
	// -------------------------------------------------------------------------

	hcpEnabled := config.Spec.OVNCentral.HCP.Enabled != nil &&
		*config.Spec.OVNCentral.HCP.Enabled

	centralNamespace := config.Namespace
	if hcpEnabled && config.Spec.OVNCentral.HCP.Namespace != "" {
		centralNamespace = config.Spec.OVNCentral.HCP.Namespace
	}

	ovnCentralReplicas := int64(config.Spec.OVNCentral.HCP.Replicas)

	if hcpEnabled {
		// Kubernetes default is 3, but direct yaml.Unmarshal() does not apply
		// CRD defaults.
		if ovnCentralReplicas == 0 {
			ovnCentralReplicas = 3
		}
	} else if config.Spec.OVNCentralMode == "single" {
		ovnCentralReplicas = 1
	} else {
		ovnCentralReplicas = int64(len(config.Status.MatchingNodeAddresses))
	}

	// kubeovn.ovnCentralNodeIPs
	ovnCentralNodeIPs := nodeIPs

	if hcpEnabled {
		addresses := make([]string, 0, ovnCentralReplicas)

		for i := 0; i < int(ovnCentralReplicas); i++ {
			addresses = append(
				addresses,
				fmt.Sprintf(
					"ovn-central-%d.ovn-central.%s.svc",
					i,
					centralNamespace,
				),
			)
		}

		ovnCentralNodeIPs = strings.Join(addresses, ",")
	}

	// -------------------------------------------------------------------------
	// TLS
	// -------------------------------------------------------------------------

	enableSSL := false
	if config.Spec.Networking.EnableSSL != nil {
		enableSSL = *config.Spec.Networking.EnableSSL
	}

	tlsCipherSuites := strings.Join(
		config.Spec.Networking.TLSCipherSuites,
		",",
	)

	// kubeovn.ovnCentralTLSEnv
	ovnCentralTLSEnv := fmt.Sprintf(
		"- name: ENABLE_SSL\n"+
			"  value: %q\n"+
			"- name: TLS_MIN_VERSION\n"+
			"  value: %q\n"+
			"- name: TLS_MAX_VERSION\n"+
			"  value: %q\n"+
			"- name: TLS_CIPHER_SUITES\n"+
			"  value: %q",
		strconv.FormatBool(enableSSL),
		config.Spec.Networking.TLSMinVersion,
		config.Spec.Networking.TLSMaxVersion,
		tlsCipherSuites,
	)

	// kubeovn.componentTLSArgs
	var componentTLSArgs strings.Builder

	if config.Spec.Networking.TLSMinVersion != "" {
		fmt.Fprintf(
			&componentTLSArgs,
			"- --tls-min-version=%s\n",
			config.Spec.Networking.TLSMinVersion,
		)
	}

	if config.Spec.Networking.TLSMaxVersion != "" {
		fmt.Fprintf(
			&componentTLSArgs,
			"- --tls-max-version=%s\n",
			config.Spec.Networking.TLSMaxVersion,
		)
	}

	for _, suite := range config.Spec.Networking.TLSCipherSuites {
		fmt.Fprintf(
			&componentTLSArgs,
			"- --tls-cipher-suites=%s\n",
			suite,
		)
	}

	// -------------------------------------------------------------------------
	// External OVN Central
	// -------------------------------------------------------------------------

	nbPort := int64(config.Spec.ExternalOVNCentral.NBPort)
	if nbPort == 0 {
		nbPort = 6641
	}

	sbPort := int64(config.Spec.ExternalOVNCentral.SBPort)
	if sbPort == 0 {
		sbPort = 6642
	}

	ovnNbPort := int64(6641)
	ovnSbPort := int64(6642)

	if config.Spec.InstallMode == "dataPlaneOnly" {
		ovnNbPort = nbPort
		ovnSbPort = sbPort
	}

	controllerReplicas := int64(len(config.Status.MatchingNodeAddresses))
	if config.Spec.InstallMode == "dataPlaneOnly" && controllerReplicas > 2 {
		controllerReplicas = 2
	}

	return map[string]interface{}{
		// Existing helper values.
		"nodeCount": int64(len(config.Status.MatchingNodeAddresses)),
		"nodeIPs":   nodeIPs,

		"ovs-ovn": upgradeStrategyMap,
		"ovn":     versionCompatibilityMap,

		"runAsUser": runAsUser,

		// ovn-central helpers.
		"centralNamespace":   centralNamespace,
		"ovnCentralReplicas": ovnCentralReplicas,
		"ovnCentralNodeIPs":  ovnCentralNodeIPs,

		// HCP OVN DB addresses.
		"ovnNbAddress": config.Spec.OVNCentral.HCP.NBAddress,
		"ovnSbAddress": config.Spec.OVNCentral.HCP.SBAddress,

		// External OVN DB addresses.
		"externalOvnNbAddress": externalOVNAddress(
			config.Spec.ExternalOVNCentral.NBEndpoint,
			nbPort,
		),
		"externalOvnSbAddress": externalOVNAddress(
			config.Spec.ExternalOVNCentral.SBEndpoint,
			sbPort,
		),

		// OVN DB ports.
		"ovnNbPort": ovnNbPort,
		"ovnSbPort": ovnSbPort,

		// TLS helpers.
		"ovnCentralTLSEnv": ovnCentralTLSEnv,
		"componentTLSArgs": strings.TrimSuffix(componentTLSArgs.String(), "\n"),

		//ovn-controller replicas for dataPlaneOnly mode
		"controllerReplicas": controllerReplicas,
	}
}
